/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lol;

/**
 *
 * @author utilizador
 */
public class Lol {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        String a[] = {"beriberi aterroar\n" +
"albatross afilhar\n" +
"commune clandestinidade\n" +
"bourses basnio\n" +
"chromosome cascavel\n" +
"ailment advireis\n" +
"battlecry arrumador\n" +
"atomizer antropomorfose\n" +
"callisthenic branquial\n" +
"centimetre camisao\n" +
"collier ciclicamente\n" +
"bookkeeper banquetear\n" +
"apolitical amor\n" +
"choroid carvalho\n" +
"backup aquilhado\n" +
"catheter calcorrear\n" +
"breakpointing bemqueira\n" +
"bowed bastidor\n" +
"blooper bacaafero\n" +
"bedstead assenhorear\n" +
"comic circunstancia\n" +
"clank cavalaria\n" +
"clansman cavaleira\n" +
"bessemer atomicidade\n" +
"colchester chumaaar\n" +
"adroit acostagem\n" +
"atom antropogenesia\n" +
"aniseikonic alpinismo\n" +
"campfire brinquedo\n" +
"assyria antihemorroidal\n" +
"baku arcaizante\n" +
"chipping carrapato\n" +
"antiresonance amear\n" +
"bovine bastante\n" +
"arbitrative andrologia\n" +
"baronesses arrebanho\n" +
"cheney caraveleiro\n" +
"alligator agredis\n" +
"behove associabilidade\n" +
"confiscator colitigante\n" +
"asylum antipolaatico\n" +
"arden angola\n" +
"booty barbar\n" +
"carafe canhamo\n" +
"compulsory coaptidao\n" +
"come circular\n" +
"climbable centralizar\n" +
"backbiter aprouvera\n" +
"bribe bemquisermos\n" +
"casuistry caixeirada\n" +
"clerical centaiureo\n" +
"clothesbrush cerzir\n" +
"appreciate analgesia\n" +
"alcoa afixo\n" +
"condoner coitaria\n" +
"bellhop astarias\n" +
"bloodbrother azulclaro\n" +
"campiness brioso\n" +
"civil caucionar\n" +
"brotherly bibliomania\n" +
"alba afilhado\n" +
"chronic cascoso\n" +
"booklet bantologia\n" +
"catalina caixote\n" +
"appetizer amuo\n" +
"backspace aquando\n" +
"chattahoochee captar\n" +
"browsing bichar\n" +
"activator academismo\n" +
"backscatter apupo\n" +
"atavism antiquaassimo\n" +
"achievable absteria\n" +
"bitmap avenha\n" +
"candle brotar\n" +
"carjacker cabotinagem\n" +
"china caro\n" +
"babysitter apriorismo\n" +
"confect colatitude\n" +
"abusable abismal\n" +
"absent abaulemos\n" +
"arithmetising aniversariar\n" +
"agility adveio\n" +
"canonist bugigangaria\n" +
"coleus chupadura\n" +
"alarming afiadeira\n" +
"bsd biglobular\n" +
"ado aconchegar\n" +
"allophonic agridam\n" +
"affirm adesao\n" +
"channelizers cantarejo\n" +
"antediluvian alvura\n" +
"baulky arterioscleratico\n" +
"bourgeois basilicata\n" +
"augury apartar\n" +
"betty atrigueirado\n" +
"anhydrously almocreve\n" +
"anchorwoman algebricamente\n" +
"allier agredimos\n" +
"brawn beligerancia\n" +
"bleak aviso\n" +
"catenate calcedania\n" +
"browne bicanao\n" +
"cockpit checkin\n" +
"acorn abstiveres\n" +
"blacklister avicena\n" +
"ames alavancar\n" +
"compensate clerocracia\n" +
"braze beliscao\n" +
"conceptional cobro\n" +
"caper burburinhar\n" +
"colicky churrascaria\n" +
"boiling baldada\n" +
"adorer acordar\n" +
"appearer amperaametro\n" +
"cancer broncoscopia\n" +
"acaclairs causticar\n" +
"boyer batista\n" +
"bloomington babuaano\n" +
"bewhisker atrofiar\n" +
"aside antevaaeis\n" +
"appositional anal\n" +
"athletic antivarialico\n" +
"complexion clorofilino\n" +
"bunghole bizantinismo\n" +
"abelard aaaimo\n" +
"avocation apor\n" +
"alimentary agiotagem\n" +
"aquaculture ancudo\n" +
"bulletin biscainho\n" +
"accrue absorvente\n" +
"clause cefalailgico\n" +
"assure antigrevista\n" +
"argybargy anilinar\n" +
"biofeedback autodisciplina\n" +
"cagoule boticairio\n" +
"beforehand assimilador\n" +
"alaric afeto\n" +
"better atribuiaao\n" +
"amateurism ajuaaze\n" +
"allocation agrida\n" +
"bligh axiomaitica\n" +
"autocorrelates apercetivo\n" +
"concise coeficiente\n" +
"aquanaut andadeiro\n" +
"bully bisonte\n" +
"bleacher avisador\n" +
"bootleggeds barba\n" +
"adonis aconselhador\n" +
"billposters autobiografia\n" +
"arian animalao\n" +
"confound colonizaaao\n" +
"button bombagem\n" +
"breathe bemquerer\n" +
"burlingame bochechao\n" +
"barberry arpoeiro\n" +
"bateman arruaar\n" +
"colostomy cimeiro\n" +
"boonies baralhada\n" +
"barflys arraaoamento\n" +
"boohoo bandolinista\n" +
"bows batedela\n" +
"amendment alar\n" +
"acidoses abstivaramos\n" +
"ashland anteposto\n" +
"boozer barbaresco\n" +
"adkins aclimatizar\n" +
"boston barracario\n" +
"basaltic arrendar\n" +
"alongside aguardentoso\n" +
"alexander afortalezar\n" +
"babbage aprendiz\n" +
"associator antiespiritualismo\n" +
"bottling barrigal\n" +
"burble bmw\n" +
"blair avieres\n" +
"beaner ascensor\n" +
"apocrypha amontar\n" +
"blueblooded bactaria\n" +
"cackler borra\n" +
"bilingualism autagrafo\n" +
"burnable bode\n" +
"agribusinesses advier\n" +
"blazoning avirias\n" +
"afield adjacente\n" +
"climate centopeia\n" +
"aorta amigar\n" +
"arithmetise anita\n" +
"beekeeping assertor\n" +
"collate ciame\n" +
"boer balanaa\n" +
"boldface baldrocar\n" +
"affecter adeque\n" +
"arlington anomia\n" +
"calvinist bravio\n" +
"alcoholism afliaao\n" +
"atonality antroponaamico\n" +
"avail aplaistico\n" +
"cantabile bulaacio\n" +
"adjustable acitrinar\n" +
"blockhead azinhaga\n" +
"begotten assinta\n" +
"appointee anafrodisia\n" +
"commemoration cirzais\n" +
"civet caucionairio\n" +
"cheap caqueirada\n" +
"champlain canil\n" +
"bengal atartarugado\n" +
"charisma capia\n" +
"collage chuvinhar\n" +
"allele agouro\n" +
"canonicalizes bugalho\n" +
"aggravate adulterar\n" +
"airfare aerabico\n" +
"bridle benemerente\n" +
"botcher barreira\n" +
"berth atividade\n" +
"bet atracadoiro\n" +
"comprehensibility coadjuvar\n" +
"arkwright anojar\n" +
"aggrandizement adulterador\n" +
"bandmaster arguam\n" +
"anxious amianto\n" +
"blockier azinheira\n" +
"astrophysics antipatriatico\n" +
"caecitis borrifo\n" +
"cafacas botanica\n" +
"airspeed aerotransportado\n" +
"blacksmith avidez\n" +
"colitis chutar\n" +
"bot barrado\n" +
"bisector avaro\n" +
"appellant ampliar\n" +
"compass clave\n" +
"banner arkansas\n" +
"briton berna\n" +
"agleam advenhamos\n" +
"cahoot botim\n" +
"annie alterante\n" +
"animalism alocuaao\n" +
"command circunvizinho\n" +
"bouvier basta\n" +
"bearable asculo\n" +
"arithmetical anisar\n" +
"chucklingly casposo\n" +
"caricaturist cabidos\n" +
"auditory aparceirar\n" +
"arcanas aneladura\n" +
"anguilla almirantado\n" +
"bifocal auraafice\n" +
"battening arruinemos\n" +
"cerebrate canaa\n" +
"coddle cher\n" +
"carbonation caatico\n" +
"bloodletting baaaa\n" +
"chairlady candura\n" +
"biochemist autodeterminaaao\n" +
"chigger carmina\n" +
"cannes brutus\n" +
"attributionally apanhamoscas\n" +
"ascertainable anteniforme\n" +
"buckingham bilheteiro\n" +
"carjackers cabotinismo\n" +
"blowup baciliforme\n" +
"bullyboy bispado\n" +
"bootee barateio\n" +
"accidental abracadabra\n" +
"bloated azeitoneiro\n" +
"abrogate abastanaa\n" +
"claudius cedro\n" +
"antimalarial amazelar\n" +
"arabic aandice\n" +
"apotheoses amortecer\n" +
"camberley breca\n" +
"blister azedume\n" +
"anglosaxon almeida\n" +
"alkyl agnosticismo\n" +
"bagful araola\n" +
"bestubble atraaao\n" +
"clichacas centeeiro\n" +
"conciliate codonatairio\n" +
"annoyer altifalante\n" +
"bluecollar bactericida\n" +
"ankle alquaamico\n" +
"breviary bemquiser\n" +
"bostonian barracento\n" +
"aquiline andar\n" +
"agave adotante\n" +
"bureaucratisation boasfestas\n" +
"archiver anglafono\n" +
"brusque bidirecional\n" +
"ballard areado\n" +
"adjunctive acionar\n" +
"belgrano assopradela\n" +
"cofferdams chipre\n" +
"blip azedia\n" +
"bedding assalto\n" +
"aircrew advocacia\n" +
"adaptive acedancia\n" +
"balfour arcoso\n" +
"bright benim\n" +
"bee assente\n" +
"censorship camiliano\n" +
"ageold adstrito\n" +
"bookkeep banquete\n" +
"annoyance alteza\n" +
"canon buda\n" +
"bakery arcada\n" +
"accentual abolitivo\n" +
"aspiration anteveremos\n" +
"applier anaerabio\n" +
"abjection aaoteado\n" +
"acct absorver\n" +
"acrobat abulas\n" +
"alienable agastar\n" +
"adventurer acudam\n" +
"antipodean ambrasio\n" +
"conclusive coentrada\n" +
"bucharest bilbau\n" +
"baloney aresteiro\n" +
"antedate alvoroao\n" +
"caleb braganaao\n" +
"assisi anticosmatico\n" +
"adair acastica\n" +
"breathing bemquereraaeis\n" +
"conceit cobracoral\n" +
"ascription anteparar\n" +
"baklava arcaico\n" +
"compromising coalhadouro\n" +
"central camoniana\n" +
"century campina\n" +
"bedpost assassino\n" +
"bolivar baleeiro\n" +
"accessors abraaadeira\n" +
"broadcasting berrar\n" +
"burg boataria\n" +
"avocado apoquentar\n" +
"backward aquisgrana\n" +
"checkin caracol\n" +
"cackly borrabotas\n" +
"alewives aforrar\n" +
"bijou auspicioso\n" +
"circus catequizante\n" +
"aab aquilo\n" +
"belittle assotar\n" +
"ascriptive anteparo\n" +
"backus aquino\n" +
"agonizer advertancia\n" +
"bessel atombar\n" +
"burger boato\n" +
"confusable colores\n" +
"blanketers avindo\n" +
"bagger arbasculo\n" +
"chicanery caricaturar\n" +
"backpedalled apudorado\n" +
"annulus altruaasta\n" +
"church cassiopeia\n" +
"adherence achegar\n" +
"chairmens canego\n" +
"chaconne canceraageno\n" +
"blowdried bacento\n" +
"brigadoon bengala\n" +
"changer cantadoira\n" +
"associate antidigestivo\n" +
"abseiling abaular\n" +
"assemblywoman anti\n" +
"autocorrelation aperfilhar\n" +
"alphabetizer aguemos\n" +
"brachia batucar\n" +
"caterwaul calcinante\n" +
"catholicity caldas\n" +
"calculi bradejar\n" +
"backwoodsmens aquosidade\n" +
"charmed capital\n" +
"chimera carnificina\n" +
"adequate achatar\n" +
"anded algodres\n" +
"bluejacket badala\n" +
"antiquarianism ambulancia\n" +
"banbridge argila\n" +
"clam cauteleiro\n" +
"comradely cobaltite\n" +
"anchor alfredo\n" +
"buff bioganese\n" +
"authorisation apelabilidade\n" +
"argue anidrite\n" +
"adore acordante\n" +
"blackball averiguemos\n" +
"astronaut antipapa\n" +
"clemson cenografia\n" +
"angel alicerce\n" +
"botched barrar\n" +
"cliffhanging centigrama\n" +
"caitiff boulevard\n" +
"attempt aonde\n" +
"bernoulli atintar\n" +
"atomization antropomorfizar\n" +
"aero adanis\n" +
"anthropologist amailgama\n" +
"channelize cantar\n" +
"chorines carunchoso\n" +
"catharses calcite\n" +
"arrears anteaa ra\n" +
"aeolian adaigio\n" +
"aldermens afluir\n" +
"banknote aristotalico\n" +
"chronography caseiro\n" +
"blackberry averigues\n" +
"bringer beraalio\n" +
"alcohol aflautar\n" +
"balkanises ardil\n" +
"cluck chacotear\n" +
"adjutant aclimatar\n" +
"centurion campestre\n" +
"colloid cidadao\n" +
"ancestry alfragide\n" +
"carnivore cacau\n" +
"compunction coaquisiaao\n" +
"calligraphist branquear\n" +
"clave cefaloide\n" +
"belying astucioso\n" +
"anodise alucinar\n" +
"castigator cair\n" +
"bishopric ave\n" +
"angie alienismo\n" +
"automatise apetrechar\n" +
"caddy borrar\n" +
"barometer arreador\n" +
"abba aajax\n" +
"anagrammatically aleo\n" +
"astrologist antioquia\n" +
"candystriped brumoso\n" +
"ballooning arengueiro\n" +
"billionfold auto\n" +
"careerism cabereis\n" +
"condemner coibais\n" +
"breakable bemdizer\n" +
"altaic ai\n" +
"bloodroot babado\n" +
"barbarize aromaticidade\n" +
"bric bemquisessem\n" +
"cartographic caderno\n" +
"achieve absteriam\n" +
"basal arremetida\n" +
"cageyness bote\n" +
"chicle caritativo\n" +
"attain anunciativo\n" +
"bionic automaitico\n" +
"classify cear\n" +
"basemen arrestar\n" +
"communing clareira\n" +
"casteth caiporismo\n" +
"calligraphic branqueadura\n" +
"chiropractor carregal\n" +
"armourplate anseio\n" +
"bravo beliche\n" +
"arthurian antedarias\n" +
"cod cheiro\n" +
"chantilly cantina\n" +
"bleating avizinhar\n" +
"beatrice asneirada\n" +
"arty antedeu\n" +
"autocracy aperiadico\n" +
"cognoscente chopin\n" +
"bobbysoxers baionetada\n" +
"bloggers azotar\n" +
"barn arranjadela\n" +
"battleground arsanio\n" +
"autoloader apetibilidade\n" +
"choppy cartoonista\n" +
"breakthrough bemqueira\n" +
"acquirement abstruso\n" +
"balalaika arcanjo\n" +
"arraigning antaalope\n" +
"adapted acavalado\n" +
"anaesthetically alegro\n" +
"appenders amplo\n" +
"chickenhearted carinhoso\n" +
"cardiopulmonary caber\n" +
"aircraft advirtamos\n" +
"bagging arbaatrio\n" +
"centrer campainheiro\n" +
"authenticate apedrar\n" +
"animalcule almotolia\n" +
"aspen antevejo\n" +
"casehardening cafezeiral\n" +
"burt boie\n" +
"carjacked cabotagem\n" +
"cablecast bordo\n" +
"cogitation choaa\n" +
"bestseller atormentador\n" +
"coating chaparia\n" +
"billionaire autismo\n" +
"capsicum busaalis\n" +
"anaesthetiser aleixo\n" +
"arguer anidro\n" +
"bigamy aureolar\n" +
"bittiness avental\n" +
"cardin cabedal\n" +
"chrism casablanca\n" +
"certainty canalhismo\n" +
"altitude aiguia\n" +
"balloon arenairio\n" +
"bella assunaao\n" +
"ares angular\n" +
"compacares coador\n" +
"accident abraao\n" +
"checksumming caracterizante\n" +
"bait arcaaasmo\n" +
"commissar citologia\n" +
"augustinian aparvoar\n" +
"barefoot arquitetor\n" +
"calumny brasonar\n" +
"chirography carrazeda\n" +
"ageism adquirir\n" +
"amide albarda\n" +
"chamfers caniaal\n" +
"bulk bis\n" +
"central camiseira\n" +
"chartist capitel\n" +
"bro bibliotecairio\n" +
"cambric brejeiro\n" +
"being associar\n" +
"attendance apacrifo\n" +
"balboa arcebispado\n" +
"betsy atrepar\n" +
"buffoonery biologismo\n" +
"beige associado\n" +
"bluenose badalao\n" +
"collude cientaafico\n" +
"bang arguitivo\n" +
"acetaminophen absteraaeis\n" +
"buttonhole bombaistico\n" +
"coalescent chance\n" +
"blackstone avidos\n" +
"cairo botsuana\n" +
"brainpower beberete\n" +
"bastard arrotador\n" +
"broncobuster bexigoso\n" +
"aortic amigdalar\n" +
"adductor acetileno\n" +
"bernard atil\n" +
"auric apavonar\n" +
"agglutinate adubo\n" +
"beijing assocializar\n" +
"boyd batista\n" +
"agitate advenha\n" +
"backyard ar\n" +
"accord abrio\n" +
"boomerang barafustar\n" +
"angus almoaadeira\n" +
"blustery bagalho\n" +
"beer assessorial\n" +
"airedale advocatura\n" +
"cloister cerquinho\n" +
"assemblage antevisses\n" +
"arrest anteato\n" +
"blame aviesse\n" +
"caretaker cabias\n" +
"cliometric ceraafero\n" +
"backdoor aprouvermos\n" +
"bedrock assear\n" +
"codependency chiante\n" +
"clump chafariz\n" +
"amtrak alcunhar\n" +
"colosseum cima\n" +
"baleful arcoceleste\n" +
"blueblack bacorada\n" +
"belmopan astroide\n" +
"churchgoer casta\n" +
"beating asnal\n" +
"bowstring batedeira\n" +
"balancedness arcar\n" +
"cockofthewalk chaveta\n" +
"chastity caprichoso\n" +
"cocoon cheireta\n" +
"ashram anterioridade\n" +
"brady beaitico\n" +
"backstroke aquidelrei\n" +
"characterisers capado\n" +
"atavist antique\n" +
"byroad boqueirao\n" +
"antidisestablishmentarianism amarguradamente\n" +
"anglicisation alinhavo\n" +
"carthage cadela\n" +
"absenteeism abc\n" +
"brewster bemquiserdes\n" +
"accolade abrelatas\n" +
"armonk anseie\n" +
"aperiodicity amiudemos\n" +
"claspknives cavernoso\n" +
"campsite brita\n" +
"aspirant antevereis\n" +
"concierge codificar\n" +
"bluegreen baculiforme\n" +
"bittern avenham\n" +
"anemometry alibilidade\n" +
"caw calorao\n" +
"antwerp amiade\n" +
"bloodstone babedo\n" +
"codex chicago\n" +
"capturer candida\n" +
"bacchus apropriador\n" +
"coldhearted chumbar\n" +
"brickyard beneditina\n" +
"comfy circunspeto\n" +
"codices chicharro\n" +
"cantonment bulha\n" +
"chapel canzarrao\n" +
"bailiwick arborista\n" +
"collisional ciclovia\n" +
"as antipedagagico\n" +
"blundering bafejar\n" +
"campanological brincar\n" +
"childbearing carnaaao\n" +
"autistic apendicite\n" +
"aerator adamascar\n" +
"abs abastecer\n" +
"cambodian brejeirada\n" +
"bacates bigodear\n" +
"arborvitae andy\n" +
"coinage choupal\n" +
"bondsmens banana\n" +
"clomps cerradura\n" +
"clinton ceramico\n" +
"armlet anseias\n" +
"butch bolhar\n" +
"biddable aula\n" +
"attainment anzoleiro\n" +
"abilene aaorda\n" +
"boundary basbaque\n" +
"climatic centraafuga\n" +
"allot agridam\n" +
"centroid campesino\n" +
"collusive cientificar\n" +
"conflictual colmatagem\n" +
"bankable aristateles\n" +
"address acerrimamente\n" +
"chastisement caprichar\n" +
"actinide abvio\n" +
"centigrades camionete\n" +
"academe ablativo\n" +
"barnardos arranjismo\n" +
"burma bochechudo\n" +
"argent anho\n" +
"blunderingly bafejo\n" +
"amazon ajudada\n" +
"bolter balote\n" +
"chambray caniaa\n" +
"axiological aprazeres\n" +
"civilization caulaacola\n" +
"ammonium albufeirar\n" +
"autocorrelated apercetibilidade\n" +
"capacitative bumbum\n" +
"aquaria andadura\n" +
"concentrator cobre\n" +
"coextensive chincalhar\n" +
"beguiler assintas\n" +
"captivating byte\n" +
"alliess agredir\n" +
"botanist barrancos\n" +
"besmirch atoladeiro\n" +
"americanisation alarme\n" +
"ashanti anteporta\n" +
"agoniser adversairio\n" +
"auricular apavorante\n" +
"careerer caberei\n" +
"aaron angela\n" +
"arctangent angloluso\n" +
"comparable claustra\n" +
"charioteer capelo\n" +
"accordant abrolhar\n" +
"collaboration chuva\n" +
"cocaine charcoso\n" +
"boswell barradela\n" +
"cobblestone chapiscar\n" +
"achiever absteve\n" +
"broadminded besante\n" +
"codger chicaria\n" +
"again adorar\n" +
"chub caso\n" +
"ambition ajustar\n" +
"airspace aerossol\n" +
"anoint aludir\n" +
"clip cerca\n" +
"confession colegiatura\n" +
"bicameral audiofrequancia\n" +
"acapulco abocanhar\n" +
"arrogation antecoro\n" +
"billy autobomba\n" +
"baste arroubamento\n" +
"cloudscape cestaria\n" +
"caber bordadura\n" +
"clomp cerradoiro\n" +
"adirondack acidafilo\n" +
"chancellorship canjuge\n" +
"commence cirzamos\n" +
"confined colidir\n" +
"anticlimactically amaragem\n" +
"collegiate ciclapico\n" +
"alto ailcool\n" +
"colon cig\n" +
"collusion ciente\n" +
"blanchard avilanar\n" +
"chorley carvalheira\n" +
"bobbings bainheiro\n" +
"antiracist ameaaar\n" +
"chenille carbanico\n" +
"aspersion antevendo\n" +
"chink carolismo\n" +
"clever centasimo\n" +
"au apaniguamos\n" +
"cleric centaagrado\n" +
"accountant absinto\n" +
"buxton bombear\n" +
"alexis afrancesar\n" +
"calumet brasileiro\n" +
"bracketings bazafia\n" +
"canvasser bulidela\n" +
"bondsmen bananal\n" +
"board baguete\n" +
"anthology amado\n" +
"bloodlust baaibai\n" +
"chancellorships cano\n" +
"biography autofotografia\n" +
"armouried anseies\n" +
"coercive china\n" +
"baksheesh arcaidia\n" +
"chinchilla carol\n" +
"committally city\n" +
"battle arrumadeira\n" +
"annette alteraaao\n" +
"bakersfield arcabuzeiro\n" +
"baccalaureate aprisionar\n" +
"bipolar autossuficiancia\n" +
"biller autarca\n" +
"banyan armaria\n" +
"bawler articulante\n" +
"chalcedony caneleiro\n" +
"blasphemous avioletar\n" +
"coincide choupana\n" +
"bentley atelier\n" +
"biennium auraacula\n" +
"analysis alfabetairio\n" +
"cockleshell chavao\n" +
"colourisations cinegatico\n" +
"antagonise alvejar\n" +
"carver cadula\n" +
"afore adjudicatairio\n" +
"candler brucelose\n" +
"bloodshot babadouro\n" +
"ballymoney arganil\n" +
"backstop aquele\n" +
"confronter colorante\n" +
"changeless cansul\n" +
"browse bichaneiro\n" +
"circumlocution catavento\n" +
"calorimeter braseiro\n" +
"congruency combativo\n" +
"commemorate cirza\n" +
"asocial antevejam\n" +
"capsular buscapolos\n" +
"bridgeport beneficiador\n" +
"calculated bracejo\n" +
"algorithmically afumar\n" +
"adjunct acional\n" +
"afrikaans administrativo\n" +
"aver apodrentar\n" +
"andy alhosporros\n" +
"athleticism antivaarus\n" +
"animalization aloirar\n" +
"chose carvoeiro\n" +
"bittersweet avenhas\n" +
"banisher arico\n" +
"brazil belize\n" +
"barbette arqueadura\n" +
"abasement ansia\n" +
"androgen alhear\n" +
"admen acobardar\n" +
"canada british\n" +
"alaska afiambrar\n" +
"autofocus aperuado\n" +
"centralization camodo\n" +
"circumference catastrafico\n" +
"analytical alfabetizar\n" +
"barbiturate arqueiro\n" +
"argentine angustiar\n" +
"appendectomy amplificativo\n" +
"claret cavalidade\n" +
"box batela\n" +
"additivity acepipe\n" +
"arkansan anoitecer\n" +
"commencement cirzamos\n" +
"asheville anteportaria\n" +
"boilerplate balda\n" +
"club cevada\n" +
"commercialization citania\n" +
"awhile aprazamos\n" +
"atoll antropogenatico\n" +
"chic carl\n" +
"both barreta\n" +
"arguable anidrido\n" +
"carnality cacam\n" +
"barclay arquiducado\n" +
"chuntering cassinga\n" +
"cassava caicos\n" +
"alluring agror\n" +
"channelise cantanhede\n" +
"ability aaores\n" +
"betrothal atravessar\n" +
"caribbean cabide\n" +
"asymptotic antiquam\n" +
"byname bonito\n" +
"combustibility circense\n" +
"calendar braguas\n" +
"bubonic bilaminado\n" +
"carve caducidade\n" +
"burlier bochecha\n" +
"compellable cleptofobia\n" +
"breaker bemfazer\n" +
"catechist calarico\n" +
"arachnid aandio\n" +
"collie ciclastomo\n" +
"beggary assinatura\n" +
"admiral acoito\n" +
"chlamydia carrinha\n" +
"befit assim\n" +
"bastardy arroto\n" +
"cnn chalreta\n" +
"adventist actuplo\n" +
"confiscate coliseu\n" +
"bury boieira\n" +
"berliner atiaa\n" +
"additional acentual\n" +
"buddy binoculizar\n" +
"bolsterer balneoterapia\n" +
"carnival cacatua\n" +
"colombia cifrante\n" +
"chg careza\n" +
"caustic calibragem\n" +
"anaesthetisers aleluia\n" +
"aerofoil adarito\n" +
"concede cobra\n" +
"anywhere amigalhaao\n" +
"alike agilizar\n" +
"chinamens caroao\n" +
"bollinger balico\n" +
"balladry ardume\n" +
"biter avenaar\n" +
"apartheid amimia\n" +
"allocate agricultura\n" +
"ceres canadiano\n" +
"calligraphy branqueio\n" +
"cay caloria\n" +
"apprise anamona\n" +
"affidavit aderancia\n" +
"begun assis\n" +
"bushwhackings bojudo\n" +
"chlorinate carroaao\n" +
"aston antimataria\n" +
"bring beraairio\n" +
"borosilicate baricentro\n" +
"complimenter coaaao\n" +
"action acabrunhado\n" +
"clashing caveiroso\n" +
"brazilian belmiro\n" +
"cockfighting chateza\n" +
"boson barqueta\n" +
"cofactor chincar\n" +
"awning aprazaavel\n" +
"birthright avante\n" +
"alto aijesus\n" +
"celebrator camarata\n" +
"commissariat citoplaismico\n" +
"biog autoestima\n" +
"chronic casebre\n" +
"calfskin braictea\n" +
"bilevel australopiteco\n" +
"almoner aguaadura\n" +
"bujumbura biprisma\n" +
"collinear ciclone\n" +
"cocos cheirinha\n" +
"computing cobaio\n" +
"cerebellum camuraar\n" +
"approbate anao\n" +
"barkleys arrancar\n" +
"clitoral cereal\n" +
"boathooks bailarino\n" +
"anglofrench aljustrel\n" +
"allis agremiaaao\n" +
"aslant anteveja\n" +
"abbey aalhavo\n" +
"comply coaadura\n" +
"artefact antedamos\n" +
"coltrane cineteatro\n" +
"coherency choramingas\n" +
"boulevard basailtico\n" +
"bitterroot avenhamos\n" +
"breed bemquererias\n" +
"canonicalizations bufo\n" +
"cocci charcutaria\n" +
"botulism barrosao\n" +
"akin afazeres\n" +
"cattery caldoverde\n" +
"communiques clarico\n" +
"chloride carroaada\n" +
"colwyn cinturao\n" +
"betoken atravanco\n" +
"censurable camilo\n" +
"beekeepers asserto\n" +
"congresswomen combater\n" +
"charcoal capear\n" +
"avuncular apostolicidade\n" +
"astute antiperiadico\n" +
"americium alastrar\n" +
"arithmetized anmp\n" +
"antagonizers alvitrar\n" +
"blacken avessia\n" +
"appetisingly amulherar\n" +
"appetite amulherengar\n" +
"careerist caberem\n" +
"apoplexy amores\n" +
"aeolus adalberto\n" +
"challenging canheiro\n" +
"abusive abissal\n" +
"caracas canfora\n" +
"condemnable coherdar\n" +
"bandsman arguamos\n" +
"ballfields arejo\n" +
"avertible apolania\n" +
"aphelion amofinar\n" +
"affect adequamos\n" +
"bedsit assembleia\n" +
"chairlift caneaas\n" +
"berlitz atiaar\n" +
"bowel bastilha\n" +
"annelida alter\n" +
"combinatorics cipreste\n" +
"antagonistic alvim\n" +
"assessment anticatico\n" +
"chooser cartilha\n" +
"bequeath atentatario\n" +
"ballcock areeiro\n" +
"approver anatar\n" +
"budge binomial\n" +
"cantaloupe bulais\n" +
"abstractionist aberta\n" +
"blew axioma\n" +
"avarice aplicada\n" +
"attachaca anulador\n" +
"barrier arredor\n" +
"agrarian adviasseis\n" +
"apartment aminoaicido\n" +
"breastings bemqueraaeis\n" +
"cocksure chefiar\n" +
"clarendon cavalheiroso\n" +
"asylumseekers antiprotao\n" +
"chairman caneco\n" +
"awake apostura\n" +
"blotter bacanalizar\n" +
"cipher catalao\n" +
"asap antefosso\n" +
"aware aprastamo\n" +
"amphibia alcobacense\n" +
"allotter agride\n" +
"benumbed atenaao\n" +
"bulking bisava\n" +
"boobytrap bandolear\n" +
"cannibalise bruxelas\n" +
"anaconda alegado\n" +
"chapter capa\n" +
"chaetognath cancionista\n" +
"billie autenticamente\n" +
"barbershop arquatipo\n" +
"bilateral austrailia\n" +
"bashful arrevesar\n" +
"chroma cascagrossa\n" +
"atmosphere antropocantrico\n" +
"approximatively anc\n" +
"belfry assombroso\n" +
"brunswick bichouro\n" +
"beleaguer assombrear\n" +
"acidic abstinente\n" +
"condensely coibis\n" +
"beadsmen asa\n" +
"colourblindness cinaibrio\n" +
"brubeck bicharrao\n" +
"bundy bivalancia\n" +
"confettis coleta\n" +
"catharsis calcografar\n" +
"ammeter alberto\n" +
"aconite abstiverem\n" +
"boudoir barrote\n" +
"anticommunist amarelo\n" +
"attenuator apaixonar\n" +
"bowyer batel\n" +
"cambridge brejeirote\n" +
"candlepower bruce\n" +
"bona bambino\n" +
"brigantine bengalas\n" +
"comparison claustromania\n" +
"ballast areal\n" +
"choleric cartela\n" +
"abort abaixar\n" +
"breeding bemqueres\n" +
"compartmentalisation clausular\n" +
"aminobenzoic albergariaanova\n" +
"comicality circunstanciar\n" +
"battledore arrumar\n" +
"coedits chilena\n" +
"biggie auriculado\n" +
"also aguo\n" +
"carousal cachao\n" +
"adoptable aconsoantar\n" +
"befitting assimetria\n" +
"avis apontar\n" +
"compliance clotilde\n" +
"axis aprazia\n" +
"arrogance anteclaissico\n" +
"arbitrator andromanaaaca\n" +
"beefy assertar\n" +
"barker arrancao\n" +
"backhoe aproveitar\n" +
"accession abotoar\n" +
"aye aprazidos\n" +
"chardonnay capelada\n" +
"affordable adietar\n" +
"ac acalito\n" +
"boloneys balizador\n" +
"commentate cisma\n" +
"banking aristocratizar\n" +
"axes aprazerei\n" +
"brim bento\n" +
"chocolate cartada\n" +
"cardsharper caberai\n" +
"anticipative amante\n" +
"actress acalentar\n" +
"addresser aceso\n" +
"amniocenteses alcantara\n" +
"aftermost adoentar\n" +
"brainwash beco\n" +
"apotheosizing amorzeiro\n" +
"conflicting colmado\n" +
"antisemitism amedrontador\n" +
"americanization alasca\n" +
"chastiser capricho\n" +
"akimbo afazer\n" +
"alabamans afeiaoar\n" +
"aqua ancorar\n" +
"casualty caixa\n" +
"chad cancerizar\n" +
"causation calhe\n" +
"anatolia alferes\n" +
"backdate aprouveres\n" +
"causer calhoada\n" +
"classifier ce\n" +
"circuital cataplana\n" +
"biased atumultuar\n" +
"clog ceroulas\n" +
"buffeting biografista\n" +
"betas atracao\n" +
"chartings capitaotenente\n" +
"coasttocoast chantre\n" +
"bong bancarrota\n" +
"begin assincronia\n" +
"abnormal abaale\n" +
"accretion absorvedor\n" +
"collative ciancia\n" +
"areawide angrense\n" +
"bellman astrametro\n" +
"affluent adicional\n" +
"businesswomen bolaavia\n" +
"backless aproximar\n" +
"cockeyedly chasco\n" +
"acne abstiveram\n" +
"blogs azotoso\n" +
"conceptive coca\n" +
"condescension coimbrao\n" +
"behave assisado\n" +
"chino carpela\n" +
"comparator claustrar\n" +
"canticle bulbiforme\n" +
"bonneville bandeirante\n" +
"antiphonal ambolo\n" +
"broadband berra\n" +
"callback brande\n" +
"classless ceata\n" +
"bungee bivaque\n" +
"antarctic alvor\n" +
"adverbial acudis\n" +
"busybody boletineiro\n" +
"according abrunhal\n" +
"armless anseiam\n" +
"chickenlivered caario\n" +
"clattery cedilha\n" +
"authoritarianism apelativo\n" +
"break bemditoso\n" +
"benson ateia\n" +
"androgenic alheio\n" +
"bambi argao\n" +
"android alho\n" +
"bouracae basilical\n" +
"completable cloral\n" +
"beaconsfield arvoar\n" +
"add acefailico\n" +
"batterer arrulhar\n" +
"cognizable chofrar\n" +
"arafat andorinho\n" +
"bracer batucada\n" +
"centreline campanula\n" +
"byronismyah borato\n" +
"bask arroba\n" +
"circumlocutory catecismo\n" +
"cadmium borrego\n" +
"castellated caipira\n" +
"anthropocentric amadrinhar\n" +
"clasper cavernaacola\n" +
"adsorbent acotovelar\n" +
"anonymity aluno\n" +
"conceive cobranaa\n" +
"ards angorai\n" +
"compaq claudicante\n" +
"aggie adubadela\n" +
"collide ciclaptico\n" +
"chinstrap carpete\n" +
"behaver assistancia\n" +
"arum antedizer\n" +
"bounded basbaqueira\n" +
"administer acobertar\n" +
"adventurism acudi\n" +
"animal almofariz\n" +
"buckminsterfullerene bilionairio\n" +
"asexuality antepasto\n" +
"censurer caminhante\n" +
"clime centrifugar\n" +
"actionable acaaclico\n" +
"aberrantly aalborg\n" +
"broccoli bessa\n" +
"brighten benguela\n" +
"compartmentalise clausura\n" +
"cider castor\n" +
"aeneid adagiar\n" +
"characterization capao\n" +
"chromosphere casco\n" +
"ballpoint areomatrico\n" +
"among alcalino\n" +
"brougham biblioteconomia\n" +
"additive acentuar\n" +
"choler carteiro\n" +
"blender axial\n" +
"cato caldeiro\n" +
"ate antiquo\n" +
"bencher atado\n" +
"cassock cailculo\n" +
"afterhours adoaante\n" +
"backplane apunhalante\n" +
"boron bariao\n" +
"callaghan brancor\n" +
"abstinent abenaoar\n" +
"battledress arrumo\n" +
"barnacle arranjao\n" +
"bathroom arruaanem\n" +
"asbestosis anteguarda\n" +
"carbonization cabaaeis\n" +
"coffer chio\n" +
"arsenic antedados\n" +
"canvas bulhar\n" +
"bezel atualista\n" +
"bishopsgate aveia\n" +
"antique ameaaa\n" +
"bely astuciar\n" +
"chiropractic carregador\n" +
"assume antigario\n" +
"assenting antialcalino\n" +
"bailsman arbustaiceo\n" +
"barnett arranque\n" +
"child carne\n" +
"acidification abstinha\n" +
"azov apreensario\n" +
"bridgeable beneficente\n" +
"acrylate aburguesar\n" +
"clutter chala\n" +
"barbara arnold\n" +
"citronella caatrico\n" +
"auditor aparatoso\n" +
"chador canceriforme\n" +
"aim advirem\n" +
"bongo banco\n" +
"artillerymen antederdes\n" +
"churchmens castanholar\n" +
"abortion abaixoassinado\n" +
"aesthetic aden\n" +
"bod baixamar\n" +
"avalon aplaudir\n" +
"adultly acrescer\n" +
"centralizer camomila\n" +
"artillery antederam\n" +
"barbedness arpao\n" +
"chivvy carrilhonar\n" +
"compile clique\n" +
"clearing celibatairio\n" +
"ammonia albufeira\n" +
"chairperson canela\n" +
"carlow cabriolice\n" +
"breathtakingly bemquererao\n" +
"capricious burriqueiro\n" +
"anticline amarante\n" +
"abortionist abalada\n" +
"areola angulairio\n" +
"admonitory acompridar\n" +
"cavitation caloraafero\n" +
"amsterdam alcoviteiro\n" +
"clubfoot chacal\n" +
"berlioz atiaador\n" +
"bilinear autadromo\n" +
"arrestable anteboca\n" +
"amok alcalinizar\n" +
"but bolhante\n" +
"bottlegreen barricar\n" +
"cavalry californiano\n" +
"assess antibioterapia\n" +
"coercer chimpanza\n" +
"advisee acusativo\n" +
"borer barbudo\n" +
"cohabitation chora\n" +
"adiposes acicular\n" +
"bursitis boiardo\n" +
"checklists caracoleta\n" +
"chamois caniao\n" +
"bandage argolada\n" +
"confuser colorimetria\n" +
"confidant coletanea\n" +
"clothespegs cesariano\n" +
"bowline batata\n" +
"bay artificioso\n" +
"comfortable circunscritivo\n" +
"carcase cabe\n" +
"background aprovar\n" +
"banner arles\n" +
"anaesthetizers alentar\n" +
"can britanismo\n" +
"businessmens bolacheiro\n" +
"abrogator abastardar\n" +
"allclear agonia\n" +
"clotheshorse cerzis\n" +
"baroquely arrebentao\n" +
"cloner certeiro\n" +
"babbitt aprendizado\n" +
"brainwasher bedelhar\n" +
"addressability acertar\n" +
"caressive cabia\n" +
"codetermine chibatada\n" +
"compatriot clemente\n" +
"applicability anacoreta\n" +
"classlessness cearai\n" +
"bushland boio\n" +
"centrifuge campanudo\n" +
"abstain abelhamestra\n" +
"biomolecule autohemoterapia\n" +
"authoritative apelidar\n" +
"accepted abordar\n" +
"biaxial audacaassimo\n" +
"bothy barretada\n" +
"brandywine beijocadela\n" +
"bimonthly autoclismo\n" +
"bogglingly balaastica\n" +
"caustic calia\n" +
"cavemens calmante\n" +
"bubble bijetiva\n" +
"an amiadas\n" +
"arose aansula\n" +
"complaining clivar\n" +
"aurora apavorar\n" +
"closefitting certo\n" +
"apias amoladura\n" +
"busks bolchevizante\n" +
"balkanisation ardente\n" +
"clad causal\n" +
"bayesian artifaacio\n" +
"chairmanship canecada\n" +
"aryan antedou\n" +
"conception cobris\n" +
"breech bemquereremos\n" +
"adventitious acuda\n" +
"cager botar\n" +
"ballsy aresta\n" +
"bodega baixel\n" +
"bindweed autocorreaao\n" +
"cadger borregada\n" +
"anomaly alumaanio\n" +
"boatmens bailomania\n" +
"aimless advires\n" +
"collard ciaitica\n" +
"cochran charlotte\n" +
"berkelium atestante\n" +
"beechwood assento\n" +
"amalgam aizimo\n" +
"coexistence chincada\n" +
"bookmarker banzar\n" +
"cartooning cadigo\n" +
"brabham batracoide\n" +
"accommodate abrenunciar\n" +
"combinational cio\n" +
"antenna ama\n" +
"bedouin assassinar\n" +
"bnp bagdade\n" +
"aziz apreender\n" +
"brouhaha bica\n" +
"calming brasa\n" +
"bison avela\n" +
"berlin ateu\n" +
"avoid aposentadoria\n" +
"categorization calcairio\n" +
"anticlimactic amar\n" +
"asserter antiaristocraitico\n" +
"comedian circulatario\n" +
"catawba calada\n" +
"cometary circunferencial\n" +
"cessation canastrado\n" +
"boastful bailador\n" +
"chessman cardinal\n" +
"bosnia baronizar\n" +
"characteriser capadeira\n" +
"blonde azul\n" +
"arizona anodizar\n" +
"bombproof bambalear\n" +
"cash caibam\n" +
"amoco alcaicer\n" +
"chandler cansas\n" +
"camden bremen\n" +
"bromide besuntao\n" +
"avitaminosis apoplexia\n" +
"caucasoid calendairio\n" +
"callus braquicafalo\n" +
"capilano burel\n" +
"briefing benfeitor\n" +
"alienist agendar\n" +
"coexistent chincadela\n" +
"autoclave aperaltar\n" +
"cole chupachupa\n" +
"archaisers anestesiar\n" +
"ashford anteporto\n" +
"begrime assintais\n" +
"appealer amp\n" +
"bluebird bacoquismo\n" +
"chickpea carisma\n" +
"cameroon brighton\n" +
"compromise coalhada\n" +
"autotransformer apio\n" +
"arithmetised aniversairio\n" +
"binding autocontrolo\n" +
"activist acaicio\n" +
"aliphatic agitabilidade\n" +
"abnegation abaalas\n" +
"bullhead biscoitar\n" +
"bodice baixia\n" +
"bethel atrapalhar\n" +
"calder brado\n" +
"chignon carminda\n" +
"bareheaded arquivaastico\n" +
"biconnected augusta\n" +
"chrysanthemum casinholo\n" +
"cilantro castrense\n" +
"cantor bulhao\n" +
"byway borborejar\n" +
"collectible cibercriminalidade\n" +
"collarbone cianico\n" +
"cockney chaveiro\n" +
"bay articulatario\n" +
"avowed apostolado\n" +
"beluga astrorei\n" +
"allspice agro\n" +
"actinium acabadote\n" +
"catarrh calaao\n" +
"billow autoavaliaaao\n" +
"chuckle caspa\n" +
"antarctica alvoraaar\n" +
"bronchiole betoneira\n" +
"clover cetanico\n" +
"affair adequam\n" +
"ashlaring anteprojeto\n" +
"compartmentalize clava\n" +
"apostate amorfismo\n" +
"clan cavador\n" +
"apportionment anais\n" +
"bouquet basilar\n" +
"anaemia alegante\n" +
"bargainer arraia\n" +
"ascendant antemural\n" +
"bombardment balsemao\n" +
"ablatively aaucarar\n" +
"catheterise calculador\n" +
"catechism calar\n" +
"adhere achega\n" +
"burglarproof bobalhao\n" +
"bifurcation auralia\n" +
"ca caldeu\n" +
"agrarian adviaramos\n" +
"binnacle autocromia\n" +
"cfo canceladura\n" +
"baedeker aranha\n" +
"congenial colunaivel\n" +
"byelaws bondoso\n" +
"bathyscaphes arruda\n" +
"clericalism centaiurico\n" +
"callgirls brandura\n" +
"beermat assetar\n" +
"cloudcuckooland cessarfogo\n" +
"absorption abeirar\n" +
"bailable arborescente\n" +
"approacher anancio\n" +
"compressibility coadunabilidade\n" +
"conjugate comeaamos\n" +
"angry almejo\n" +
"clwyd chalaaar\n" +
"alchemy afixar\n" +
"charlady capilaridade\n" +
"antic amanho\n" +
"abnormality abaale\n" +
"abidjan aaoiteira\n" +
"anticyclonic amargo\n" +
"alzawahiri aitono\n" +
"bake arcabuz\n" +
"ati antivirulento\n" +
"amethystine alaxico\n" +
"caribou cabidela\n" +
"chauvinist capuz\n" +
"aphrodite amojudo\n" +
"apposition anaitema\n" +
"calculability bracarense\n" +
"buchenwald bilha\n" +
"anchorpeople algazarra\n" +
"armoury anselmo\n" +
"bluesy badameco\n" +
"bander argua\n" +
"absurdity abesourar\n" +
"abettor aanas\n" +
"blurringly baforar\n" +
"adenauer achada\n" +
"chasuble caprino\n" +
"accomplish abrigo\n" +
"accusation abstencionista\n" +
"biconvex augustal\n" +
"celsius cambota\n" +
"boggy balbuciante\n" +
"colourize cinemateca\n" +
"brewer bemquiseram\n" +
"clocker cerimania\n" +
"bituminous aventura\n" +
"cardiff cabeceiro\n" +
"becket aspiratario\n" +
"catalyse cajuada\n" +
"anthill amachucar\n" +
"boxwood batesola\n" +
"breakdown bemfalante\n" +
"arrayer antaatese\n" +
"callee brandir\n" +
"autorepeat apincelar\n" +
"blueings baculino\n" +
"city caucaisico\n" +
"beardless asfaltar\n" +
"ague adviessem\n" +
"claus cedrodomato\n" +
"aeroplane adegueiro\n" +
"byers boneco\n" +
"attorney apalpadeira\n" +
"angular almiscarar\n" +
"airconditioned advirtais\n" +
"beady asador\n" +
"chair candor\n" +
"bunkum blindado\n" +
"bse bignania\n" +
"animated aloquete\n" +
"baller areia\n" +
"californium bramir\n" +
"ballad ardor\n" +
"anvil amiadem\n" +
"chihuahua carmo\n" +
"acc abole\n" +
"conciliation codornizao\n" +
"caulking calhamaao\n" +
"clergywoman censurador\n" +
"caginesss boticairia\n" +
"adoring acorde\n" +
"abjure aaoute\n" +
"cardsharp caberaaeis\n" +
"abomination abade\n" +
"arbitrager androceu\n" +
"chaotic cantoneiro\n" +
"architrave anginoso\n" +
"coed chifrar\n" +
"binomial autodecomposiaao\n" +
"chilblain carmona\n" +
"bilious autamato\n" +
"concentrative cobre\n" +
"carven caduco\n" +
"carapace cantaro\n" +
"bluebottle bacteriaiceo\n" +
"cliveden cerebelite\n" +
"confrontationally coloraametro\n" +
"carloading cabrinha\n" +
"biostatistics autonomia\n" +
"blank avinde\n" +
"call brancacento\n" +
"confucian colorear\n" +
"chipboard carraaa\n" +
"burk bocadoce\n" +
"bullyings bispaivel\n" +
"bootprints barbado\n" +
"apprehender analogia\n" +
"cappuccino burrico\n" +
"aggrandise adular\n" +
"aristotle aniquilar\n" +
"chilli carneireiro\n" +
"astonishment antimilitar\n" +
"ballymena argamassar\n" +
"bamako arganteo\n" +
"chemiluminescence carateraastica\n" +
"archbishopric aneurose\n" +
"bangle arguo\n" +
"clique cerceador\n" +
"baggage arar\n" +
"coherer chorao\n" +
"clonk certidao\n" +
"anther amachucadela\n" +
"alternating aiguaforte\n" +
"appomattox anailise\n" +
"chop cartolina\n" +
"cessna canastro\n" +
"anklebone alqueirao\n" +
"aught aparelhar\n" +
"bohemia balbuciar\n" +
"bargainbasement arrabujar\n" +
"aldridge afogar\n" +
"chorea caruma\n" +
"bootleg baraatono\n" +
"causerie calhoar\n" +
"absorber abecedairio\n" +
"browsable bichanar\n" +
"bladderwort aviera\n" +
"codfish chicana\n" +
"coming circunvagante\n" +
"calorie brasao\n" +
"banal argentaafero\n" +
"brasserie beirense\n" +
"bayonet artificialidade\n" +
"applicator anaadrico\n" +
"assaultiveness antevirmos\n" +
"briber bemquisesse\n" +
"austere apaziguas\n" +
"ago advertimos\n" +
"augur apartadiao\n" +
"baselessness arrepelo\n" +
"antiquation ambulativo\n" +
"chemurgy caravela\n" +
"blower bacharelado\n" +
"arte antedaiveis\n" +
"amour alcatroar\n" +
"cnaa chalreio\n" +
"aeneas adagial\n" +
"arcane anemiante\n" +
"advocative acutilante\n" +
"around anta\n" +
"agitative advenhais\n" +
"castigation caiqueiro\n" +
"barrett arrecuar\n" +
"bellflower astaitico\n" +
"caster caipirada\n" +
"bare arquitetanica\n" +
"cannery bruto\n" +
"abutment abissaanio\n" +
"amid albatroz\n" +
"agaa adonisar\n" +
"appointer anafrodita\n" +
"carnivorous cacaual\n" +
"alphabetise ague\n" +
"amish albergue\n" +
"cliquish cerdoso\n" +
"boone baralha\n" +
"blab averigue\n" +
"chiropodist carrear\n" +
"collocation cid\n" +
"chichester caridade\n" +
"abbott aalvaro\n" +
"caviare calo\n" +
"camembert brevetar\n" +
"adjective acidificante\n" +
"agar adormentar\n" +
"agenda adscrever\n" +
"cannibalisations bruxedo\n" +
"agitprop advenham\n" +
"bernardino atilho\n" +
"bream bemqueiramos\n" +
"artery antedarais\n" +
"bleater aviventar\n" +
"centrepiece campainhada\n" +
"cognitives chofrada\n" +
"bonemeal bancada\n" +
"arise animante\n" +
"casaba cafeaana\n" +
"bimbo autocarro\n" +
"clearups celso\n" +
"another alva\n" +
"anchoritic algarismo\n" +
"beret atermal\n" +
"avower apostolar\n" +
"coediting chila\n" +
"cockle chauvinismo\n" +
"circumflex catatua\n" +
"autocue apertadoiro\n" +
"anecdote aliais\n" +
"bloch azerbaijao\n" +
"calibre bramanismo\n" +
"commie citador\n" +
"bsa biglandular\n" +
"airwomen afagoso\n" +
"aphrodisiac amojo\n" +
"chaca¢telaine casmurrada\n" +
"charabanc capacheiro\n" +
"commutation clarividancia\n" +
"aries animalizar\n" +
"chattel captura\n" +
"abstemious abelhudo\n" +
"astir antimanio\n" +
"confracares colore\n" +
"clipper cercania\n" +
"clothe cerzimos\n" +
"cascade cafeicultura\n" +
"bullock biscouteira\n" +
"antonym amestrar\n" +
"bacate bigode\n" +
"annealer altar\n" +
"clock cerejeira\n" +
"attender apafase\n" +
"arras antaapodes\n" +
"boatclubs bailar\n" +
"attentionality apagar\n" +
"anion alperce\n" +
"agenda adriano\n" +
"amoebic alcaidemor\n" +
"cashier caiba\n" +
"conical comboio\n" +
"ampere alcino\n" +
"backstage aquecer\n" +
"cokey chucha\n" +
"birthstone avaqueirado\n" +
"citizenly catolicidade\n" +
"conference coleaao\n" +
"annum altruaastico\n" +
"complacence clisterizar\n" +
"character capacho\n" +
"cock charme\n" +
"boutonniacares bassorai\n" +
"coleridge chupadoiro\n" +
"afresh adjuvante\n" +
"assemble antevista\n" +
"chit carretel\n" +
"arne ansiao\n" +
"analyse alfa\n" +
"atmospherically antropoganese\n" +
"analogise alevante\n" +
"batting arrumaaos\n" +
"asiatech anteva\n" +
"banana argentino\n" +
"bimetallism autociclo\n" +
"communist clarigo\n" +
"announcer alterno\n" +
"comparative claustral\n" +
"aspire anteveriam\n" +
"citric catrafilar\n" +
"abounding abalico\n" +
"arapaho andrade\n" +
"ascorbic anteontem\n" +
"cohoes chorinquento\n" +
"appreciation analisador\n" +
"captious bvl\n" +
"closeset cerveja\n" +
"clumsy chafurdar\n" +
"affix adeus\n" +
"aristophanes aninhar\n" +
"communicable claanica\n" +
"attachs anunciada\n" +
"agglomeration adubadura\n" +
"clouding cesta\n" +
"antisemitic amedalhar\n" +
"carriage cacifo\n" +
"accustom abstenhais\n" +
"candlewick bruma\n" +
"assemblywomen antiaareo\n" +
"bromsgrove betao\n" +
"bevel atrito\n" +
"coexist chinca\n" +
"arianism animalejo\n" +
"brontosaurus bexiguento\n" +
"chafe cancro\n" +
"aileron advirdes\n" +
"carryall cactiforme\n" +
"blare avinhao\n" +
"ayrshire apreao\n" +
"abuse abismar\n" +
"angiosperm alijar\n" +
"argumentation anilar\n" +
"boil balcanico\n" +
"bowlegs batalhante\n" +
"bangladeshi argumento\n" +
"clinker cepudo\n" +
"adirondacks acidar\n" +
"conceal cobiaa\n" +
"cincture casuloso\n" +
"appetising amuleto\n" +
"cabot borgonha\n" +
"burial bocaaberta\n" +
"commando cirurgiao\n" +
"animadversion almofadar\n" +
"brigandage bengalao\n" +
"chaffer candeio\n" +
"ascetically anteocular\n" +
"bbc artimanha\n" +
"anaesthetization alemanha\n" +
"blowdrier bach\n" +
"bitternut avenhamos\n" +
"bereft atenuativo\n" +
"bushel boiem\n" +
"caution caliciforme\n" +
"comfortabilities circunscricional\n" +
"compton coalhadura\n" +
"cagiest botelho\n" +
"complain clitoridismo\n" +
"alsace aguitarrar\n" +
"arching angeles\n" +
"borough barico\n" +
"astor antimilitarista\n" +
"brampton beiaana\n" +
"catheterises calcular\n" +
"cashew caiar\n" +
"capitalist burlao\n" +
"aphonic amoirar\n" +
"assassinate anteviram\n" +
"chicano caricioso\n" +
"assist anticraatico\n" +
"boon barahona\n" +
"comical circunstancial\n" +
"abatement aacaro\n" +
"autocross apertadela\n" +
"acquiescent abstrair\n" +
"confracares colorau\n" +
"canonicalized bugalha\n" +
"arbiter andreia\n" +
"cloistral cerrado\n" +
"anthropomorphising amaldiaoar\n" +
"braise beethoven\n" +
"beck aspirar\n" +
"ban argelino\n" +
"breve bemquisemos\n" +
"brokerage bestificante\n" +
"abscission abate\n" +
"bespoke atomatar\n" +
"centrifugates campanha\n" +
"backgrounder aprovativo\n" +
"autonomic apicultural\n" +
"calhoun braille\n" +
"aggregate adulto\n" +
"cassocked cailice\n" +
"bowelling basto\n" +
"amherst alba\n" +
"billygoat autocapia\n" +
"condenser coicear\n" +
"canasta bromaadrico\n" +
"cleaning celebrador\n" +
"aniseed alpiaraa\n" +
"caress cabermos\n" +
"anthropometric amainar\n" +
"casehardened cafezal\n" +
"animism alpaca\n" +
"centavo caminhense\n" +
"chancer canoa\n" +
"charlatanry capim\n" +
"compatibility clemancia\n" +
"backhand aproveitabilidade\n" +
"annex alterabilidade\n" +
"backwash aquisiaao\n" +
"agglomerative adubar\n" +
"ate antiquemos\n" +
"asserted antialcoolismo\n" +
"congress comandar\n" +
"asylumseeker antipopular\n" +
"apparent amouriscar\n" +
"clusterings chai\n" +
"booming baragrafo\n" +
"atman antropanimo\n" +
"anthropic amadorismo\n" +
"chemist caraterizaaao\n" +
"chock carsega\n" +
"ache absteremos\n" +
"circumstance catenoide\n" +
"californian bramido\n" +
"borehole barbosa\n" +
"alfalfa afreguesar\n" +
"aeration adamado\n" +
"clean ceilao\n" +
"confracare colorar\n" +
"brag beataafico\n" +
"bombay baluarte\n" +
"blowdryer bacharela\n" +
"clapton cavalete\n" +
"amusement aldeao\n" +
"catanddog calaadeira\n" +
"aliasing agancia\n" +
"coleslaw chupador\n" +
"appalachia amossar\n" +
"commodity civilizacional\n" +
"brooding biatico\n" +
"blowout bachicar\n" +
"bivalve aveo\n" +
"clubhouse chacinar\n" +
"coin chorudo\n" +
"bridesmaid benefaacio\n" +
"appellation ampliativo\n" +
"argon aniao\n" +
"antiquity ameaaador\n" +
"beale ascatico\n" +
"benedict atamancar\n" +
"bola baldio\n" +
"adventuresome acudamos\n" +
"anastomoses alfarrobal\n" +
"baster arroubo\n" +
"camshaft britador\n" +
"certify cananico\n" +
"byelection boneca\n" +
"alerters afora\n" +
"audiovisual aparalaipis\n" +
"cicada castificar\n" +
"calais bpsm\n" +
"con cobarde\n" +
"associativity antiescorbatico\n" +
"cancellate bromofarmio\n" +
"cobbler chapinheiro\n" +
"cavalrymen caligrafar\n" +
"chanciness canonicidade\n" +
"butyl bombardeiro\n" +
"brilliancy benjamin\n" +
"bulletproof biscar\n" +
"baggageman arara\n" +
"bandwagon arguente\n" +
"beefcake asseraao\n" +
"bade aragonas\n" +
"appleton anabolizante\n" +
"clunker chafurdo\n" +
"applicable anacranico\n" +
"bc artrapodes\n" +
"conceded cobracapelo\n" +
"acupressure acariciativo\n" +
"cfc cancela\n" +
"christianity casamentar\n" +
"adman acne\n" +
"arousal antaadoto\n" +
"cdt caluniar\n" +
"agnatha advenho\n" +
"adducer acessario\n" +
"broadbrush berrador\n" +
"confectionist colcheia\n" +
"candelabra bronquial\n" +
"bonaide bambolim\n" +
"chattanooga captor\n" +
"candidate bronzeador\n" +
"biracial autossugestionar\n" +
"calcite brabante\n" +
"bodieds baixinho\n" +
"complicate clube\n" +
"coneys colar\n" +
"charlottesville capitaaao\n" +
"ancestor alforjar\n" +
"admiration acolchetar\n" +
"bilbao australaisio\n" +
"biblical audaavel\n" +
"babushka apressurar\n" +
"broacher bernoulli\n" +
"alfa afrechar\n" +
"camouflager brilho\n" +
"burgundian boca\n" +
"arbitrament androfobia\n" +
"bamboozle argel\n" +
"blizzard azeitonar\n" +
"chapel cantuplo\n" +
"brookside biberao\n" +
"antivenin ameno\n" +
"bow bastao\n" +
"backbencher aprouver\n" +
"cavalryman caliginar\n" +
"aquarius andaimaria\n" +
"apple anaabal\n" +
"babcock apresentador\n" +
"bedspread assemelhar\n" +
"changeable canseira\n" +
"congruity combinador\n" +
"bummer bissemanal\n" +
"cavan caligrafia\n" +
"able aaudar\n" +
"addable acefalia\n" +
"collapsibility chuviscoso\n" +
"carrot caco\n" +
"bromine beta\n" +
"awe apraza\n" +
"asynchronism antiquam\n" +
"annexation alterador\n" +
"bobble baiona\n" +
"benz atenas\n" +
"commutate clarito\n" +
"alkaline aglutinaaao\n" +
"atheist antirraquaatico\n" +
"barstow arreigada\n" +
"aegrotat adagiairio\n" +
"comeuppance circunflexo\n" +
"cabochon borges\n" +
"antispasmodic ameijoeira\n" +
"amelia alameda\n" +
"acetic absterais\n" +
"charitable capilaiceo\n" +
"annihilative alterego\n" +
"carnet cacarejo\n" +
"bode baixar\n" +
"cadenza borratada\n" +
"anemometer aliar\n" +
"chomsky cartilagaaneo\n" +
"balinese ardancia\n" +
"bluey badana\n" +
"bedstraw assentada\n" +
"bail arborescancia\n" +
"absentee abaulemos\n" +
"clarifier cavalo\n" +
"anastigmatic alfarroba\n" +
"cabinetwork bordel\n" +
"blabbermouth averigueis\n" +
"bassist arromba\n" +
"anodyne alucinoganio\n" +
"batavia arrozeira\n" +
"astrologer antinomismo\n" +
"clinger centurial\n" +
"angler alimentividade\n" +
"builtin bipolar\n" +
"abide aao\n" +
"basrelief arroio\n" +
"ablative aaucareiro\n" +
"barrow arreganhada\n" +
"ballerina areis\n" +
"biology autognose\n" +
"boxiness batepapo\n" +
"atrium anual\n" +
"chilton carniaal\n" +
"checksummed caracterizaaao\n" +
"chomp cartice\n" +
"airmass aeroplanismo\n" +
"chisel carreiro\n" +
"chiffon carmelo\n" +
"coachmens chamejante\n" +
"comfort circunscriaao\n" +
"belonging astrologia\n" +
"arteriole antedaraaamos\n" +
"beersheba asseverar\n" +
"antic amarfanhar\n" +
"concavity cobertura\n" +
"cenobite camelino\n" +
"clattering ceder\n" +
"clavichord cegas\n" +
"calabash bpa\n" +
"celanese camarada\n" +
"aspidistra anteverei\n" +
"behavioured assistir\n" +
"attentional apagador\n" +
"brassier beirute\n" +
"colatitude chularia\n" +
"calamitous braaa\n" +
"backhander aproveitante\n" +
"chitin carriaa\n" +
"bewail atrofia\n" +
"centenarian caminheta\n" +
"bes atoucinhar\n" +
"attar ao\n" +
"adjournment acima\n" +
"cardioid cabeludo\n" +
"antipasto ambiental\n" +
"chessmens cardiologia\n" +
"ashley anteproposta\n" +
"clincher centrodireita\n" +
"assistance anticrepasculo\n" +
"angling aljubarrota\n" +
"barnabas arranjado\n" +
"atheist antissaptico\n" +
"affectation adequar\n" +
"antichrist amanio\n" +
"awake apoteose\n" +
"biometry autograifico\n" +
"affricative aditaacio\n" +
"comprehend coadjuvante\n" +
"apologizer amordaaar\n" +
"astrophysicist antipatizar\n" +
"carom cachaceira\n" +
"aureole apatite\n" +
"balsamic arfada\n" +
"aboveboard abalizar\n" +
"alterable aicido"
};
        for(int i = 0;i<10000;i++){
            for(int j=0;j<5;j++){
              System.out.print("PESQUISA "+a[i]);  
            }
            
        }
    }
    
}
